---
interval_ms: 30000
network: holesky
ethereum_rpc: https://ethereum-holesky-rpc.publicnode.com
clusters:
  - cluster_id: "0xde12c5ce1bc895c3ed8b81afcbbb55b3efff7ae9ebac5dbd2ebac3bd29474c09"
owners:
  - address: "0xd4bb555d3b0d7ff17c606161b44e372689c14f4b"
